import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

export const metadata: Metadata = {
  title: 'Nova',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

const pretendardJP = localFont({
  src: './fonts/PretendardJPVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard-jp',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${pretendardJP.variable} font-sans antialiased`}>{children}</body>
    </html>
  );
}
