import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider, QueryProvider } from './_providers';
import { Toast } from '@/shared/ui';

export const metadata: Metadata = {
  title: 'Nova',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

const pretendardJP = localFont({
  src: './fonts/PretendardJPVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-interface',
});

const wantedSans = localFont({
  src: './fonts/WantedSansVariable.woff2',
  weight: '100 900',
  display: 'swap',
  variable: '--font-hero',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' suppressHydrationWarning>
      <body className={`${pretendardJP.variable} ${wantedSans.variable} font-sans antialiased`}>
        <QueryProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem={false}
            disableTransitionOnChange={true}
          >
            <Toast />
            {children}
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
