export const KEYWORD_CATEGORY_MAP: Record<string, string[]> = {
  'Mobile App': [
    'Android',
    'iOS',
    'Flutter',
    'React Native',
    'Kotlin',
    'Swift',
    'SwiftUI',
    'Jetpack Compose',
    'Firebase',
    'Mobile CI/CD',
  ],

  Web: [
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'Next.js',
    'Vue.js',
    'Nuxt',
    'Svelte',
    'Vite',
  ],

  Backend: [
    'Java',
    'Spring',
    'Spring Boot',
    'Node.js',
    'Express',
    'NestJS',
    'REST API',
    'GraphQL',
    'JPA',
    'MySQL',
  ],

  'Full-stack': [
    'Full Stack',
    'MERN Stack',
    'MEAN Stack',
    'Next.js Fullstack',
    'BFF (Backend for Frontend)',
    'Prisma',
    'Supabase',
    'Firebase Auth',
    'API Design',
    'Monorepo',
  ],

  AI: [
    'Machine Learning',
    'Deep Learning',
    'LLM',
    'Prompt Engineering',
    'Fine-tuning',
    'RAG',
    'OpenAI API',
    'LangChain',
    'Vector Database',
    'AI Ethics',
  ],

  'Data Engineering': [
    'ETL',
    'Data Pipeline',
    'Apache Airflow',
    'Apache Spark',
    'Kafka',
    'Hadoop',
    'Data Warehouse',
    'BigQuery',
    'Snowflake',
    'Batch Processing',
  ],

  'Data Analysis': [
    'Python',
    'Pandas',
    'NumPy',
    'SQL',
    'Data Visualization',
    'Tableau',
    'Power BI',
    'A/B Testing',
    'Statistics',
    'Exploratory Data Analysis',
  ],

  Infra: [
    'AWS',
    'GCP',
    'Azure',
    'Docker',
    'Kubernetes',
    'CI/CD',
    'Terraform',
    'Nginx',
    'Load Balancer',
    'Cloud Architecture',
  ],

  Security: [
    'Cyber Security',
    'OWASP',
    'Web Security',
    'Penetration Testing',
    'Encryption',
    'OAuth',
    'JWT',
    'Zero Trust',
    'Security Audit',
    'Vulnerability Analysis',
  ],

  Networking: [
    'TCP/IP',
    'HTTP/HTTPS',
    'DNS',
    'CDN',
    'Load Balancing',
    'Network Protocols',
    'Network Security',
    'VPN',
    'Routing',
    'Switching',
  ],

  'Embedded Systems': [
    'Embedded C',
    'Microcontroller',
    'ARM',
    'RTOS',
    'Firmware',
    'IoT',
    'Raspberry Pi',
    'Arduino',
    'Device Driver',
    'Embedded Linux',
  ],

  Blockchain: [
    'Blockchain',
    'Smart Contract',
    'Ethereum',
    'Solidity',
    'Web3',
    'DeFi',
    'NFT',
    'Layer2',
    'Consensus Algorithm',
    'Cryptography',
  ],

  'Computer Vision': [
    'Computer Vision',
    'Image Processing',
    'OpenCV',
    'CNN',
    'Object Detection',
    'Image Segmentation',
    'OCR',
    'Face Recognition',
    'YOLO',
    'Vision Transformer',
  ],

  'Game Dev': [
    'Game Engine',
    'Unity',
    'Unreal Engine',
    'C# Game Dev',
    'Game Physics',
    'Multiplayer Server',
    'Game AI',
    'Rendering',
    'Shader',
    'Game Optimization',
  ],

  'System Engineering': [
    'Operating System',
    'Linux',
    'Kernel',
    'System Programming',
    'Process Management',
    'Memory Management',
    'File System',
    'Shell Script',
    'Performance Tuning',
    'Low-level Programming',
  ],

  QA: [
    'Software Testing',
    'Test Automation',
    'Selenium',
    'Cypress',
    'Unit Test',
    'Integration Test',
    'E2E Test',
    'Test Case Design',
    'QA Process',
    'Bug Tracking',
  ],
};
